using UnityEngine;
using System.Collections;
using UnityEngine.Networking;

//==============================================
// Here we have the map generated by the server
// for our panic mode!  You must collect 
// 32 teeth faster than your opponent, while
// trying not to die.  This class is mostly for
//==============================================
public class NetworkGameManager : NetworkBehaviour {

	public bool serverSarted = false;
	private int playercount = 0;
	public GameObject nm;
	public NetworkManager gameManager;

	void Start()
	{
		gameManager = nm.GetComponent<NetworkManager> ();
	}

	void Update () 
	{
		if (!serverSarted) 
		{
			if (isServer) 
			{
				//Generate the map!
				Debug.Log("This client is hosting the server.  Awaiting Client Connection.");
				serverSarted = true;
			}
		}
	}
}
